# Generated by Django 4.0.2 on 2022-03-12 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='descriptiopn',
            new_name='description',
        ),
    ]
